name: Flutter Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install lcov
        run: sudo apt-get install lcov

      - name: Get Flutter version
        id: flutter_version
        run: echo "FLUTTER_VERSION=$(grep '^flutter' .tool-versions | cut -d' ' -f2)" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run widget tests with coverage
        run: flutter test --coverage --reporter=github

      - name: Install Android SDK dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip openjdk-24
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          echo "export ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_ENV

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Install Android SDK components
        run: |
          sdkmanager "platform-tools" "platforms;android-33" "system-images;android-33;google_apis;x86_64"
          sdkmanager --update

      - name: Create and launch emulator
        run: |
          echo "no" | avdmanager create avd -n test -k "system-images;android-33;google_apis;x86_64"
          flutter emulators --create --name test
          flutter emulators --launch test

      # Requires emulator to be running
      - name: Run integration tests
        run: flutter test integration_test --coverage --merge-coverage --reporter=github
        
      - name: Generate code coverage report
        run: genhtml coverage/lcov.info -o coverage/html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/html 